version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_BACKEND_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/pongdb
      - PORT=3000
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pongdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: